In [ ]:
import os
from pathlib import Path
from IPython.display import display
import ipywidgets as widgets

# Widget-based path 
test_path = widgets.Text(
    value='./data/test',  # Default value
    placeholder='Enter test dataset path',
    description='Train Path:'
)
display(test_path)
test_dir = Path(test_path.value).expanduser().resolve()

if not test_dir.exists():
    raise ValueError(f"Test path{test_dir} does not exist!")

Mounted at /content/drive


In [ ]:
from my_module import SoccerEventDataset,SoccerEventClassifier,evaluate_model,SoccerEventClassifierV2
from torchvision.transforms import transforms
test_transform= transforms.Compose([
      transforms.Resize((224,224)),
      transforms.ToTensor(),
      transforms.Normalize([.485,.456,.406],[.229,.224,.225])
     ])
test_data = SoccerEventDataset(root_dir=test_dir, transform=test_transform)

In [3]:

from torch.utils.data import DataLoader
test_loader= DataLoader(test_data,batch_size=32,shuffle=False)

In [4]:

import torch
device='cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [5]:
model= SoccerEventClassifier().to(device)
model.load_state_dict(torch.load('/content/drive/MyDrive/FootballAnalysis/Classification-models/best_model_v4.pth'))
evaluate_model(model=model,test_loader=test_loader,device=device)

Downloading: "https://download.pytorch.org/models/efficientnet_b0_rwightman-7f5810bc.pth" to /root/.cache/torch/hub/checkpoints/efficientnet_b0_rwightman-7f5810bc.pth
100%|██████████| 20.5M/20.5M [00:00<00:00, 130MB/s] 


test accuracy: 0.8784

 Classification Report: 
              precision    recall  f1-score   support

       Cards       0.99      0.78      0.88       500
      Center       0.95      1.00      0.97       500
      Corner       0.93      0.99      0.96       500
   Free-Kick       0.79      0.68      0.73       500
        Left       0.81      0.90      0.86       500
     Penalty       0.99      0.78      0.87       500
       Right       0.70      0.99      0.82       500
      Tackle       0.97      0.78      0.87       500
 To-Subtitue       0.88      1.00      0.94       500

    accuracy                           0.88      4500
   macro avg       0.89      0.88      0.88      4500
weighted avg       0.89      0.88      0.88      4500


 confusion Matrix:
[[391   0  24  11   0   0   3  11  60]
 [  0 498   0   0   1   0   1   0   0]
 [  0   0 495   2   0   0   1   0   2]
 [  2   0   2 340  63   0  93   0   0]
 [  0   1   0  44 452   3   0   0   0]
 [  0   0   0   0  27 391  82   

0.8784444444444445