In [1]:
from google.colab import drive
drive.mount('/content/drive')
import sys
sys.path.append('/content/drive/MyDrive/FootballAnalysis')

Mounted at /content/drive


In [2]:
import torch
from torch.utils.data import DataLoader
from torchvision.transforms import transforms
from my_module import SoccerEventDataset, SoccerEventClassifier,evaluate_model

#Transformation to apply to the images
transform= transforms.Compose([
      transforms.Resize(256),
      transforms.CenterCrop(224),
      transforms.ToTensor(),
      transforms.Normalize(mean=[.485,.456,.406],std=[.229,.224,.225])
  ])

# runtime to evaluate model
device= torch.device('cuda' if torch.cuda.is_available() else 'cpu')

root='/content/drive/MyDrive/FootballAnalysis/Test' #root dir

batch_size=16

test_dataset= SoccerEventDataset(root_dir=root,transform=transform)

test_loader= DataLoader(test_dataset,batch_size=batch_size,shuffle=False)

model= SoccerEventClassifier().to(device)

model.load_state_dict(
    torch.load('/content/drive/MyDrive/FootballAnalysis/model_event_classifier.pth'
    ))
accuracy= evaluate_model(model=model,test_loader=test_loader, device=device)

Downloading: "https://download.pytorch.org/models/efficientnet_b0_rwightman-7f5810bc.pth" to /root/.cache/torch/hub/checkpoints/efficientnet_b0_rwightman-7f5810bc.pth
100%|██████████| 20.5M/20.5M [00:00<00:00, 55.7MB/s]
<ipython-input-2-a05d04caf3e7>:28: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you do

test accuracy: 0.8656

 Classification Report: 
              precision    recall  f1-score   support

       Cards       0.96      0.80      0.87       500
      Center       0.94      0.98      0.96       500
      Corner       0.90      0.97      0.93       500
   Free-Kick       0.80      0.70      0.75       500
        Left       0.79      0.92      0.85       500
     Penalty       0.98      0.77      0.87       500
       Right       0.72      0.99      0.84       500
      Tackle       0.97      0.66      0.79       500
 To-Subtitue       0.86      0.99      0.92       500

    accuracy                           0.87      4500
   macro avg       0.88      0.87      0.86      4500
weighted avg       0.88      0.87      0.86      4500


 confusion Matrix:
[[400   1  16  11   0   0   0   8  64]
 [  0 490   0   0   1   0   9   0   0]
 [  7   0 487   5   0   0   0   1   0]
 [  4   2   2 350  54   0  87   1   0]
 [  0   2   1  27 461   6   3   0   0]
 [  0   0   0   0  52 386  62   

In [ ]:
print(f'Accuracy: {accuracy}')

Accuracy: 0.8655555555555555
